### ISSUE TITLE
Any example for using the library?

### ISSUE THREAD

**Issue by xinali** [googleprojectzero/TinyInst#1]
Hello ifratric,

Thank you very much for your sharing first.
I'm very interested in the library, any plan to share some examples for using the library?

**Comment by ifratric** [comment]
Hey, if you let me know what kind of usage you had in mind and what kind of information you're missing, I could provide more, but for now:

 - If you are interested in writing a new instrumentation client, then https://github.com/googleprojectzero/TinyInst/blob/master/litecov.cpp (coverage client) could be considered an example.

 - If you are interested in using the existing coverage client (or any custom client) as a part of a larger application then take a look at the code of the example binary at https://github.com/googleprojectzero/TinyInst/blob/master/tinyinst-coverage.cpp

 - If you are interested in running the binary, then the simplest way to get it to run is something like
`litecov.exe -instrument_module notepad.exe -- notepad.exe`
or
`litecov.exe -instrument_module notepad.exe -coverage_file coverage.txt -- notepad.exe`
If you also want coverage dumped to a file.
