### ISSUE TITLE
Coverage file generated by litecov is empty on MacOS

### ISSUE THREAD

**Issue by wizche** [googleprojectzero/TinyInst#11]
I was just playing with TinyInst and trying to get coverage of /usr/bin/file on my macOS Catalina (10.15.6) and noticed that the generated coverage file is empty. Its weird because when I trace with the basic blocks option enabled (`-trace_basic_blocks`), I do see multiple `TRACE: Executing basic block` messages.

```sh
$ sudo ./Release/litecov -instrument_module file -trace_module_entries -coverage_file coverage.log -- /usr/bin/file /usr/bin/lsm
Instrumented module file, code size: 106496
TRACE: Entered module file at address 0x10ab7b49c
[!] WARNING: Relative jump to a differen module in bb at 0x10ab7410c
/usr/bin/lsm: Mach-O 64-bit executable x86_64
Process finished normally
$ ls -l coverage.log
-rw-r--r--  1 root  staff  0 Sep 12 17:25 coverage.log
$ file -v
file-5.37
```

Switching to edge coverage (`-covtype edge`) gets me one entry:
```
 $ sudo ./Release/litecov -covtype edge -instrument_module file -trace_module_entries -coverage_file coverage.log -- /usr/bin/file /usr/bin/lsm
Instrumented module file, code size: 106496
TRACE: Entered module file at address 0x1070fe49c
[!] WARNING: Relative jump to a differen module in bb at 0x1070f710c
/usr/bin/lsm: Mach-O 64-bit executable x86_64
Process finished normally
Found 1 new offsets in file
$ cat coverage.log
file+0x1349c
```

I'm compiling with AppleClang 11.0.3.11030032

**Comment by ifratric** [comment]
Hi, please see the current limitations (and workarounds :-)) of the MacOS version at https://github.com/googleprojectzero/TinyInst/blob/master/macOS/README.md

The coverage module is not currently able to extract coverage post process exit. To work around that, you can define a target method (e.g. main) and then extract coverage when the target method exists instead.

**Comment by wizche** [comment]
Thanks @ifratric, I missed the README in the macOS folder
