### ISSUE TITLE
Attach mode can't generate coverage_file on win10. 

### ISSUE THREAD

**Issue by dgh05t** [googleprojectzero/TinyInst#24]
HI,
`litecov.exe -instrument_module notepad.exe -coverage_file coverage.txt -- notepad.exe` works fine.
but the attach mode: `litecov.exe -instrument_module notepad.exe -coverage_file coverage.txt -pid 4972`
shows nothing in cmd, and the saved coverage.txt is empty.

**Comment by ifratric** [comment]
I see the issue - should be fixed now with the following commit:
https://github.com/googleprojectzero/TinyInst/commit/0a407b29ef21453a95befe126474170de67098fc
