### ISSUE TITLE
Typo in TinyInst CMakeLists.txt

### ISSUE THREAD

**Issue by r3ggi** [googleprojectzero/TinyInst#25]
There is a typo in path in CMakeLists.txt:

https://github.com/googleprojectzero/TinyInst/blob/dec3b0c6ab472700700c25569c16b74899fc6f7a/CMakeLists.txt#L60

should be:

`macOS/machtarget.cpp`

**Comment by ifratric** [comment]
Thanks for letting me know, should be fixed now!
