### ISSUE TITLE
How to link TinyInst with Visual Studio project?

### ISSUE THREAD

**Issue by hack-rabbit** [googleprojectzero/TinyInst#27]
Hello,
first of all, thank you for developing such a convenient framework.

As you noted on `README.md`, I'm trying to use this library on my Visual Studio project.
I added additional include path, link path, library filename on project configuration as usual and tried to build the solution. (Release, x64) However, I eventually failed all the times with the following error on both VS19 and VS17.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __imp_SymLoadModuleEx	ttf-fuzz	c:\Users\thegr\source\repos\ttf-fuzz\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
Error (active)	E1097	unknown attribute "no_init_all"	ttf-fuzz	C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winnt.h	3901	
Error	LNK2001	unresolved external symbol __imp_SymCleanup	ttf-fuzz	c:\Users\thegr\source\repos\ttf-fuzz\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
Error	LNK2001	unresolved external symbol __imp_SymInitialize	ttf-fuzz	c:\Users\thegr\source\repos\ttf-fuzz\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
... (86 same LNK2001 errors follow)
```

Is there a way to link the built `tinyinst.lib` file with existing Visual Studio C++ project?

**Comment by hack-rabbit** [comment]
After I found out that I have to include `xed.lib` also, I added it but the following 6 errors keep remains.
Do you have any ideas about the reasons the errors being generated?
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1097	unknown attribute "no_init_all"	ttf-fuzz	C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winnt.h	3901	
Warning	LNK4098	defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library	ttf-fuzz	c:\Users\thegr\source\repos\ttf-dev\ttf-fuzz\LINK	1	
Error	LNK2001	unresolved external symbol __imp_SymCleanup	ttf-fuzz	c:\Users\thegr\source\repos\ttf-dev\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
Error	LNK2001	unresolved external symbol __imp_SymInitialize	ttf-fuzz	c:\Users\thegr\source\repos\ttf-dev\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
Error	LNK2001	unresolved external symbol __imp_SymLoadModuleEx	ttf-fuzz	c:\Users\thegr\source\repos\ttf-dev\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
Error	LNK2001	unresolved external symbol __imp_SymFromName	ttf-fuzz	c:\Users\thegr\source\repos\ttf-dev\ttf-fuzz\tinyinst.lib(debugger.obj)	1	
```

**Comment by hack-rabbit** [comment]
I finally got it. I had to include `dbghelp.lib` too. 
I think the `README.md` should be updated in order to support people who wants the library not binary like me.

**Comment by ifratric** [comment]
FWIW, I know it won't work for everyone, but since TinyInst uses CMake, the easiest way to integrate it with another project is to have the other project also use CMake and then simply
```
target_link_libraries(your_project_target tinyinst)
```
I believe that would also take care of additional dependencies.
