### ISSUE TITLE
Broken Litecov offsets

### ISSUE THREAD

**Issue by nonetype** [googleprojectzero/TinyInst#29]
Extracting coverage with `-covtype edge` option, breaks coverage offset output.

* Tested Environment
  * Windows 10 20H2
  * TinyInst commit 374af079bb446b9a420e9c1d483dd65d9f005724
  * Visual Studio 2019 (Community 16.8.4)

**Reproduce:**
```cmd
git clone --recursive https://github.com/googleprojectzero/TinyInst.git
cd TinyInst
mkdir build
cd build
cmake -G"Visual Studio 16 2019" ..
cmake --build . --config Release

"Release\litecov.exe" -instrument_module notepad.exe -covtype edge -coverage_file cov.txt -- "notepad.exe"
```

after closing notepad, `cov.txt` file is created.
```
notepad.exe+0x1300
notepad.exe+0x1440
notepad.exe+0x1460
notepad.exe+0x1480
[snip...]
notepad.exe+0x25900
notepad.exe+0x25960
notepad.exe+0x25990
notepad.exe+0x259d0
notepad.exe+0x130000001316    <----- What happened here?
notepad.exe+0x131600001321
notepad.exe+0x132100001326
notepad.exe+0x134800001372
[snip...]
notepad.exe+0x258bf000258c6
notepad.exe+0x259000002590d
notepad.exe+0x2590d00025919
notepad.exe+0x2591f00025926
notepad.exe+0x259600002597c
notepad.exe+0x25990000259a8
notepad.exe+0x259d0000259ec
[EOF]
```

**Is this means 0x1300 to 0x1316? or broken?**

testing with `-covtype bb`, cov.txt contents is:
```
notepad.exe+0x1300
notepad.exe+0x1316
notepad.exe+0x1321
notepad.exe+0x1326
[snip...]
notepad.exe+0x25990
notepad.exe+0x259a8
notepad.exe+0x259b9
notepad.exe+0x259d0
notepad.exe+0x259ec
[EOF]
```

**Comment by ifratric** [comment]
Actually, that looks OK. Let me explain.

In TinyInst coverage, an "offset" is a 64-bit number that is meant to uniquely indentify a piece of coverage. For basic block coverage, an "offset" is indeed an offset into the binary being instrumented. However, for edge coverage, just an offset into the binary is not sufficient to uniquely identify an edge. An edge is instead identified by the combination of offsets of the previous and next basic block. Therefore, a TinyInst edge "offset" is a 64-bit number that contains a previous basic block offset in its higher 32 bits and the next offset in the lower 32 bits (except in cases where the previous basic block is unknown, e.g. outside of instrumented module, indirect jumps in some cases depending on the flags etc., in which case the previous offset is set to zero).

You can see how offsets are calculated for edge coverage here: https://github.com/googleprojectzero/TinyInst/blob/991ccd639da880cec8591c9c1b6511af82dfd533/litecov.cpp#L211

**Comment by nonetype** [comment]
Thanks for your help!
