### ISSUE TITLE
How to implement a Detach method in the Debugger class?

### ISSUE THREAD

**Issue by wangkai0351** [googleprojectzero/TinyInst#31]
In TinyInst project, I noticed that methods such as Run(Attach)/Continue/Kill are included. I want to know how to implement a Detach method?

**Comment by ifratric** [comment]
On Windows, it would involve calling DebugActiveProcessStop() and clearing appropriate structures (similar to Kill() method).
On MacOS, it would involve calling ptrace with PT_DETACH, restoring the exception handlers and possibly other tasks (Debugger::Kill() and Debugger::OnProcessExit() probably already implement most of these tasks)

**Comment by wangkai0351** [comment]
Thanks for your reply. 
I think DebugActiveProcessStop() Win32 API will kill the target process(under debugging), But in a modern debugger (such as x64dbg), the Detach method is equivalent to the process(under debugging) is still keep running and can be attached again.
（Not sure if my opinion is correct.）
