### ISSUE TITLE
Debugger::RemoteRead often crashes on macos

### ISSUE THREAD

**Issue by dazhouzhou** [googleprojectzero/TinyInst#32]
When I fuzz some targets on macos big sur, TinyInst often crashes in Debugger::RemoteRead. I can’t reproduce it, so I’m not sure if it’s a bug.
```
CRASH STACK:
 0   0x00007fff204200cd _platform_memmove$VARIANT$Haswell + 77
 1   0x000000010003c506 Debugger::RemoteRead(void*, void*, unsigned long) + 326
 2   0x000000010003caed Debugger::GetMachHeader(void*, mach_header_64*) + 45
 3   0x000000010003ee9e Debugger::GetModuleEntrypoint(void*) + 46
 4   0x000000010003fac7 Debugger::OnModuleLoaded(void*, char*) + 87
 5   0x00000001000121ff TinyInst::OnModuleLoaded(void*, char*) + 47
 6   0x000000010003ff65 Debugger::OnDyldImageNotifier(unsigned long, unsigned long, unsigned     long long*) + 821
 7   0x0000000100040380 Debugger::HandleDebuggerBreakpoint() + 272
 8   0x00000001000406b8 Debugger::HandleExceptionInternal(Debugger::MachException*) + 104
 9   0x00000001000413c6 catch_mach_exception_raise_state_identity + 566
 10  0x000000010004b4f8 _Xmach_exception_raise_state_identity + 248
 11  0x000000010004b671 mach_exc_server + 241
 12  0x0000000100040fc9 Debugger::DebugLoop(unsigned int) + 601
 13  0x000000010004219a Debugger::Continue(unsigned int) + 90
 14  0x0000000100005a60 RunTarget(int, char**, unsigned int, unsigned int) + 704
 15  0x000000010000617c main + 796
 16  0x00007fff203f9621 start + 1
```

**Comment by ifratric** [comment]
Hmm, I haven't encountered such a crash before but I'll take a look at related code, perhaps something pops up.

In the meantime, can you tell me if it reproduces only when using multiple fuzzing threads in the same process (-nthreads flag if you're using Jackalope) or also with a single fuzzing thread.

**Comment by ifratric** [comment]
Also, can you reproduce with a debug build of TinyInst (I think there might be some lines missing from that call stack due to inlinining. Also, having line numbers would be useful).

**Comment by ifratric** [comment]
I made a change that's possibly related. Can you update and see if it fixes the issue?

**Comment by dazhouzhou** [comment]
Thanks for your quick fix. This issue has been fixed. I am using Honggfuzz with TinyInst. Now it looks very stable.
