### ISSUE TITLE
The stability is not high when using -loop with target_offset.

### ISSUE THREAD

**Issue by linhlhq** [googleprojectzero/TinyInst#4]
Hi,
Thank you for publishing a great project.
I am used to developing one fuzzer. However, when run fuzzer with large `-iterations`, the stability decreases markedly when I run with `-iterations 1`. It seems that the coverage changes after each iteration. Is there any way to keep the stability of the coverage when running with large `-iterations`?

**Comment by ifratric** [comment]
Hey, unless there is another problem I haven't thought about, getting somewhat different coverage when running 1 iteration and multiple iterations is expected: In the first iteration, for example, you might encounter some initialization steps and in the second iterations they might be skipped and another path taken. There are also other reasons why a sample might result in variable coverage (e.g. different threads).

The way I'm dealing with this in a fuzzer I'm developing is: When a sample triggers new coverage, I re-run the sample a certain number of times. I split this coverage in two parts
 - "stable" coverage - this is the coverage encountered on every run with this sample and presumably depends on the sample
 - "variable" coverage - this is the coverage that I only encountered on some runs with the sample but not the others. This is the coverage that does not depend on the sample.

Variable coverage is largely ignored - it is marked as hit and ignored on future runs, but if a sample resulted only in variable coverage, it's not considered interesting.
Stable coverage is what we really want - if a sample results in new stable coverage, it is considered important.

Next week, I plan to post an update that will make these operations on coverage (e.g. coverage intersection, coverage difference) easier.

I hope this helps.

**Comment by linhlhq** [comment]
Great, I will upgrade my fuzzer.
btw: I am also looking forward to the new project that you will publish.

**Comment by linhlhq** [comment]
@ifratric, another problem with `-iterations` is that if it is large, it consumes a lot of memory, until the process's memory reaches the limit, the instrument will fail because it cannot allocate memory anymore. Do you have any advice for me on this?

**Comment by ifratric** [comment]
Wait, where exactly does the instrumentation fail? TinyInst shouldn't allocate new memory in the target process between iterations (at least not unless instrumented module gets loaded/unloaded between iterations).

**Comment by ifratric** [comment]
To give a more complete answer here, there are two kinds of memory leaks that can occur - memory leaks in the TinyInst code and memory leaks in the target process code. I would consider memory leaks in the TinyInst code serious bugs that should be fixed. Memory leaks in the target process code, we can't do much about, but we should make sure TinyInst (the parent process) handles them gracefully and doesn't crash. Some other things to consider:

Firstly, as stated above, TinyInst should only allocate memory in the target process once (per module load) when a module is getting instrumented.

Secondly, when creating a target process, TinyInst has an option to set a target process memory limit, see https://github.com/googleprojectzero/TinyInst/blob/master/debugger.cpp#L980. However, this currently isn't exposed anywhere (e.g. through a command line flag, I should also add that in the next update). Also note that the memory limit wouldn't help with TinyInst allocating memory in the target process (unless the limit doesn't apply when another process allocates memory in the target process).
 
Thirdly, a fuzzer could query memory usage of the target process *before* every iteration and, if it's determined to be too high, kill the target process.
