### ISSUE TITLE
Litecov got no coverage 

### ISSUE THREAD

**Issue by JsHuang** [googleprojectzero/TinyInst#45]
Hi, whilte using litecov to get coverage info, I found it will fail for some program , below is an example out put  with `-trace_module_entries -trace_debug_events -trace_basic_blocks` options.

```
litecov.exe -trace_module_entries -trace_debug_events -trace_basic_blocks  -instrument_module FvRT.exe  -- "C:\Program Files (x86)\FATEK\FvRT\Ver1.5\application\FvRT.exe"
Debugger: Process created or attached
Debugger: Exception 80000003 at address 00007FFF723A0770
Debugger: Unloaded module from 00000000015B0000
Debugger: Unloaded module from 0000000001D70000
Debugger: Unloaded module from 0000000001D70000
Debugger: Unloaded module from 00000000015B0000
Debugger: Exception 4000001f at address 0000000077651B72
Debugger: Loaded module FvRT.exe at 0000000000400000
Debugger: Loaded module ntdll.dll at 00000000775A0000
Debugger: Loaded module KERNEL32.DLL at 00000000766F0000
Debugger: Loaded module KERNELBASE.dll at 00000000768A0000
Debugger: Loaded module ADVAPI32.DLL at 0000000077380000
Debugger: Loaded module msvcrt.dll at 0000000075AE0000
Debugger: Loaded module sechost.dll at 0000000076670000
Debugger: Loaded module RPCRT4.dll at 0000000075940000
Debugger: Loaded module USER32.dll at 0000000075E90000
Debugger: Loaded module win32u.dll at 00000000767E0000
Debugger: Loaded module ferlib.dll at 00000000700C0000
Debugger: Loaded module GDI32.dll at 0000000076180000
Debugger: Loaded module fgud.dll at 0000000070880000
Debugger: Loaded module libcrypto-1_1.dll at 000000006FA20000
Debugger: Loaded module gdi32full.dll at 0000000075860000
Debugger: Loaded module WS2_32.dll at 0000000075BA0000
Debugger: Loaded module msvcp_win.dll at 00000000761B0000
Debugger: Loaded module libgcc_s_dw2-1.dll at 000000006E940000
Debugger: Loaded module ucrtbase.dll at 0000000077200000
Debugger: Loaded module qextserialport1.dll at 000000006CDC0000
Debugger: Loaded module mosquitto.dll at 0000000071600000
Debugger: Loaded module phonon4.dll at 00000000659C0000
Debugger: Loaded module setupapi.dll at 0000000076230000
Debugger: Loaded module QtCore4.dll at 000000006E0C0000
Debugger: Loaded module cfgmgr32.dll at 0000000077500000
Debugger: Loaded module OLE32.dll at 0000000075C10000
Debugger: Loaded module bcrypt.dll at 0000000075A00000
Debugger: Loaded module QtNetwork4.dll at 0000000065C80000
Debugger: Loaded module combase.dll at 0000000075550000
Debugger: Loaded module QtSql4.dll at 0000000061F80000
Debugger: Loaded module QtSvg4.dll at 0000000065B40000
Debugger: Loaded module SMTPEmail.dll at 0000000069980000
Debugger: Loaded module SystemLog.dll at 0000000064640000
Debugger: Loaded module fhidapi.dll at 000000006DA00000
Debugger: Loaded module MSVCR120.dll at 000000006F930000
Debugger: Loaded module SSLEAY32.dll at 0000000070D40000
Debugger: Loaded module LIBEAY32.dll at 000000006F7F0000
Debugger: Loaded module pthreadVC2.dll at 00000000715E0000
Debugger: Loaded module VCRUNTIME140.dll at 0000000070B60000
Debugger: Loaded module MSVCR100.dll at 000000006F730000
Debugger: Loaded module mingwm10.dll at 00000000015B0000
Debugger: Loaded module QtGui4.dll at 0000000001D70000
Debugger: Loaded module QtXml4.dll at 0000000002730000
Debugger: Loaded module tbaselib.dll at 00000000016D0000
Debugger: Loaded module libstdc++-6.dll at 000000006FE40000
Debugger: Loaded module libwinpthread-1.dll at 0000000064B40000
Debugger: Loaded module COMDLG32.DLL at 00000000760C0000
Debugger: Loaded module shcore.dll at 0000000075460000
Debugger: Loaded module SHLWAPI.dll at 0000000077540000
Debugger: Loaded module SHELL32.dll at 0000000076AD0000
Debugger: Loaded module COMCTL32.dll at 0000000073A50000
Debugger: Loaded module IMM32.DLL at 0000000075E10000
Debugger: Loaded module OLEAUT32.DLL at 0000000076800000
Debugger: Loaded module WINMM.DLL at 0000000074E20000
Debugger: Loaded module WINSPOOL.DRV at 00000000752B0000
Debugger: Loaded module ntdll.dll at 00007FFF722D0000
Debugger: Loaded module wow64.dll at 00007FFF71440000
Debugger: Loaded module wow64win.dll at 00007FFF71750000
Debugger: Loaded module wow64cpu.dll at 0000000077590000
Debugger: Process entrypoint reached
Instrumented module FvRT.exe, code size: 16261120
Debugger: Loaded module windows.storage.dll at 0000000074380000
Debugger: Loaded module wldp.dll at 0000000074340000
Debugger: Process exit
Process finished normally
```

The target FvRT.exe is a 32bit PE executable running on Windows 10 64bit (21H1). 
I can not get any idea what's going wrong.

**Comment by ifratric** [comment]
Does TinyInst work correctly for other programs on the same machine, e.g. does
`litecov.exe -instrument_module notepad.exe -- notepad.exe` work?

Can you retry after disabling any antivirus and antimalware programs you have running on that machine?

**Comment by JsHuang** [comment]
It works fine for notepad.exe. 
There is no antivirus software besides the windows defender. And I have also  disable denfender.
You can download and install the FvRT(V1.5.100 B21331) executabe here 
https://www.fatek.com/en/download.php?act=list&cid=154

**Comment by ifratric** [comment]
Sorry, I can't download that, it requires a user account which apparently I can't register.

I can tell you however help to start debugging it yourself. When instrumenting the binary, TinyInst will make all code in the binary not-executable. Then, whenever the target tries to execute this code, it will cause an exception that TinyInst will catch and redirect execution to the instrumented version of the code (written in another location). It seems this last step never happens. I can think of two possible reasons for this:
 1) There's something strange about the target and it doesn't report correctly where its executable code is
 2) Something is preventing the code from being marked as non-executable.
To check if 1) is the case, you can print newrange.from and newrange.to before this line
https://github.com/googleprojectzero/TinyInst/blob/b9e886de379e3e63b4e225cee0afe40caa891f7b/Windows/debugger.cpp#L556
Additionally, you should uncomment this print https://github.com/googleprojectzero/TinyInst/blob/b9e886de379e3e63b4e225cee0afe40caa891f7b/Windows/debugger.cpp#L1230
to make sure the process entrypoint is within one of the executable ranges. You can post the log again here after that.

**Comment by ifratric** [comment]
Actually, I think I know what the problem might be. It could be that the binary does not support DEP. This is a problem for TinyInst which relies on DEP exceptions as described above. It might be possible to force-enable DEP when creating a target process (and I'll look into adding that in the future), however if the target genuinely needs DEP disabled to work properly, this will cause other problems.

**Comment by JsHuang** [comment]
> Actually, I think I know what the problem might be. It could be that the binary does not support DEP. This is a problem for TinyInst which relies on DEP exceptions as described above. It might be possible to force-enable DEP when creating a target process (and I'll look into adding that in the future), however if the target genuinely needs DEP disabled to work properly, this will cause other problems.

It's true that the DEP is not enabled for the binary, after I force enable it , Tinyinst got some coverage. But has exception in instrumentation.
```
litecov.exe  -instrument_module FvRT.exe  -- "C:\Program Files (x86)\FATEK\FvRT\Ver1.5\application\FvRT.exe"
Instrumented module FvRT.exe, code size: 16261120
Exception at address 0000000004EFD469
Exception in instrumented module FvRT.exe
Code before:
00 00 00 00 00 00 00 00 43 aa
Code after:
ef 69 c2 4d 07 f8 00 75 05 e9 56 00 00 00 e9 00
Process crashed
Found 66 new offsets in FvRT.exe
```

**Comment by ifratric** [comment]
Regarding DEP, this has now been addressed by adding `-force_dep` flag to TinyInst

Regarding the other problems, it appears your target contains self-modifying code (check what the instruction at 0x01383a3b is doing). I understand this is probably not the answer you want to hear, but as stated in the README, TinyInst explicitly does not support such targets.
