### ISSUE TITLE
There is a typo in the function LiteCov::OnModuleInstrumented

### ISSUE THREAD

**Issue by cooolie** [googleprojectzero/TinyInst#5]
hello Ivan

Thank you for your great project,I found a possible b typo.
It looks like the parameter should be data->coverage_buffer_size instead of module->instrumented_code_size.

```
  // map as readonly initially
  // this causes an exception the first time coverage is written to the buffer
  // this enables us to quickly determine if we had new coverage or not
  data->coverage_buffer_remote = 
    (unsigned char *)RemoteAllocateBefore(min_address,
                                          max_address,
                                          **module->instrumented_code_size,<<?data->coverage_buffer_size**
                                          READONLY);

  if (!data->coverage_buffer_remote) {
    FATAL("Could not allocate coverage buffer");
```

[https://github.com/googleprojectzero/TinyInst/blob/master/litecov.cpp#L97](url)

**Comment by ifratric** [comment]
Oh, you are absolutely right! Fortunately, instrumented_code_size should always be larger than coverage_buffer_size, but it's still a bug. Thanks for letting me know! Fixed in https://github.com/googleprojectzero/TinyInst/commit/ff155aefe45cebb5a4fa847031532fd697c93c9d
