### ISSUE TITLE
Is there any dependencies on the initial content of the remote memory?

### ISSUE THREAD

**Issue by Inori** [googleprojectzero/TinyInst#55]
Background: I'm trying to port TinyInst to a new project that rewrite code in the target process itself as a normal process, not as a debugger, for my own usage.
 And [here](https://github.com/Inori/TinyDBR/invitations) it is. (I'll make it open source once it's done.)

Currently, I can successfully run some demos from DirectXSDK, and then I try to run some big targets.
But I found something weird. When I run the UE4 UMG UI demo within visual studio debugger, there will be an unexpected access violation writing the code segment of the target process. If I simply ignore the exception for several times, the demo can start normally. But when I run it without visual studio debugger as a normal process, it just crash.

I guess that the program runs into some uninitialized code in `instrumented_code_remote` and because it's initial content is all `0x00` and this will be explained as `add byte ptr ds:[rax], al` instructioin by the CPU, and the exception written address is exactly `rax`.
I try to initialize the remote memory with all `0xFB` which is `sti` privileged instruction, and as expected the exception above becomes `EXCEPTION_PRIV_INSTRUCTION` and proves my guess.

Then I did the same thing to the original TinyInst right after `RemoteAllocateNear` in `TinyInst::InstrumentModule` function:
```
  memset(module->instrumented_code_local, 0xFB, module->instrumented_code_size);
  RemoteWrite(module->instrumented_code_remote, module->instrumented_code_local, module->instrumented_code_size);
```
And yea the demo can not run normally when I initialized the remote memory with non-zero content. Seems it runs into an infinite loop. It can run the target normally without my modification. But I think this is because TinyInst itself is a debugger and ignores some exceptions as I did with visual studio.

**I think the behavior of the code should not be affected by the initial content of the memory**, it should be override by the real thing latter whatsoever. And it shouldn't write the target code segment either, of course.

I'm not sure if this is an issue, can you give me some advise on how to debug this problem?
I can provide the compiled binary of the demo program if you want.

**Comment by ifratric** [comment]
> It seems that the program runs into some uninitialized code in instrumented_code_remote and because it's initial content is all 0x00 and this will be explained as add byte ptr ds:[rax], al instructioin by the CPU.

Note that TinyInst won't currently work correctly on targets that contain self-modifying code. If some code section of your target changes over time (e.g. it starts as 0x00 and then later some other code changes it into something else), TinyInst will not "catch" that change. Could this explain the behavior you're seeing?

**Comment by ifratric** [comment]
1. TinyInst should never execute code inside instrumented_code_remote before writing code there. The only places where TinyInst redirects execution in the remote code buffer is in `TinyInst::TryExecuteInstrumented` and `TinyInst::HandleIndirectJMPBreakpoint`. This happens immediately after writing translated code to the same location in the buffer. E.g. in `TinyInst::TryExecuteInstrumented` execution is redirected to the address returned by `GetTranslatedAddress`. So, in theory at least, jumping to uninitialized memory inside instrumented_code_remote shouldn't happen. I suspect this is somehow related to the changes you made. I suggest investigating how execution flow ended up in the uninitialized memory in the first place. Normally, I'd use `-trace_module_entries` and `-trace_basic_blocks` for this purpose. Not sure if that still works in your project.

2. When TinyInst is acting as a debugger, only a single TinyInst thread ever interacts with a single target at one time (everything gets called from `Debugger::DebugLoop` which runs in a single thread). Your project might have changed that constraint, so you might need to add some global locking mechanisms.

**Comment by Inori** [comment]
Well, let me clarify my questions:
1. By saying `TinyInst behaves different with or without initiaze the allocated remote memory` I mean, [the original TinyInst project](https://github.com/googleprojectzero/TinyInst), not my modified version, or I won't raise this issue.

2. 
> only a single TinyInst thread ever interacts with a single target at one time

I know TinyInst is a debugger and there's only one debugging thread, for sure. What I mean is the translated code running in the target's threads, not the code which is doing the translate. There will be many target threads running at the same time, and I'm not sure if the translated code will write some global memory allocated by TinyInst, thus causing multi thread problem.

This is not an easy problem which it seems like at first look, I'm working on this bug for 3 days.
Anyhow, I'll report the progress once I have something new to share.

**Comment by ifratric** [comment]
Target running multiple threads is totally fine and expected, only the TinyInst tasks (code translation, exception handling) should be single-threaded (or properly locked).

**Comment by Inori** [comment]
OK, I figured out the problem finally.
Yes, this is a multi thread problem, unlike TinyInst which update global jump table after a debug event, at which time the system will suspend all the threads of the target process, my modified version does such things in a VEH handler, the difference is that when a VEH exception occurs, the system won't suspend any thread for us.
Thus there may be a thread updating the global jump table while another thread read the table entry at the same time, causing data race.
Fix is [here](https://github.com/Inori/TinyDBR/blob/master/TinyDBR/tinydbr.cpp#L553).
Thanks for your reply and sorry for trouble you.

**Comment by ifratric** [comment]
Awesome, I'm glad you managed to figure it out!
