### ISSUE TITLE
 Generate coverage of main module on MacOS attach mode

### ISSUE THREAD

**Issue by dgh05t** [googleprojectzero/TinyInst#60]
Hi ifratric,
Can Tinyinst generate coverage of main module on MacOS attach mode?
I tried `sudo ./litecov -instrument_module test -coverage_file coverage.txt -pid 13845` but no coverage generated.
It seems attach mode on Mac can only instrument dylib?

**Comment by ifratric** [comment]
That should certainly be supported, but it's possible that particular combination of flags wasn't sufficiently tested and there's a bug somewhere. I can take a look next week (I'm away currently). Are you running on Intel or Arm (M1)?

**Comment by dgh05t** [comment]
I'm running on Intel now, I'll test the M1 ASAP.

**Comment by ifratric** [comment]
This should be fixed now. Can you confirm?

**Comment by dgh05t** [comment]
The commit resolve the issue, thanks!
