### ISSUE TITLE
Cached instrumented code on TinyInst debugged target process

### ISSUE THREAD

**Issue by x9090** [googleprojectzero/TinyInst#64]
Hi Ivan,

I have implemented a debugger detachment routine which looks like following:

```
void LiteCov::PostDetach() {
	CollectCoverage();
	for (auto iter = instrumented_modules.begin(); iter != instrumented_modules.end(); iter++) {
		ModuleInfo *cur_module = *iter;
		RestoreExecutableCode(&(cur_module->executable_ranges));
                cur_module->ClearInstrumentations();
		//TinyInst::OnProcessExit();
	}
	DetachDebuggee(); // Note: Child handles will be closed here so we don't need to close them explicitly
}
```

The debugged process can be detached just fine and the target process runs as normal. However, one interesting behavior I noticed from the target process is that, the instrumented code will be hit and crashed immediately if i performed the same operation when the target process is being debugged, for example:

1. Open notepad.exe
2. Instrument the target process using litecov.exe: `litecov.exe  -trace_debug_events -instrument_module notepad.exe -pid <process_id>`
3. Observed the `instrumented_code_remote` buffer address: `instrumented_code_remote: 0x00007FF639380000`. Obviously, I did that by adding printf function.
4. Perform some deterministic operations on notepad.exe. For example, save the document.
5. Detach the debugger. notepad.exe should be still up and running
6. From the same notepad.exe, perform the same operation as in Step 4
7. Observe the crash on notepad.exe with the following debugging info:

```
0:017> dps 0x00007FF639380000 l5
00007ff6`39380000  00007ff6`39390008
00007ff6`39380008  00007ff6`39390008
00007ff6`39380010  00007ff6`39390008
00007ff6`39380018  00007ff6`39390008
00007ff6`39380020  00007ff6`39390008
0:017> u 00007ff6`39390008
00007ff6`39390008 cc              int     3
00007ff6`39390009 c605f0fffbff01  mov     byte ptr [00007ff6`39350000],1
00007ff6`39390010 4055            push    rbp
00007ff6`39390012 53              push    rbx
00007ff6`39390013 56              push    rsi
00007ff6`39390014 57              push    rdi
00007ff6`39390015 4154            push    r12
00007ff6`39390017 4155            push    r13
0:017> g
(1134.1ee4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
00007ff6`393b4fdc c605b9bef9ff01  mov     byte ptr [00007ff6`39350e9c],1 ds:00007ff6`39350e9c=00
0:000> u 00007ff6`393b4fdc
00007ff6`393b4fdc c605b9bef9ff01  mov     byte ptr [00007ff6`39350e9c],1
00007ff6`393b4fe3 0f1f440000      nop     dword ptr [rax+rax]
00007ff6`393b4fe8 85c0            test    eax,eax
00007ff6`393b4fea 0f8505000000    jne     00007ff6`393b4ff5
00007ff6`393b4ff0 e9a0020000      jmp     00007ff6`393b5295
00007ff6`393b4ff5 e900000000      jmp     00007ff6`393b4ffa
00007ff6`393b4ffa c6059cbef9ff01  mov     byte ptr [00007ff6`39350e9d],1
00007ff6`393b5001 837def50        cmp     dword ptr [rbp-11h],50h
0:000> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00000000`00000000     : 000001c6`b575708c 00000000`0a840665 00007ff6`39461218 00000039`00001134 : 0x00007ff6`393b4fdc
0:000> .exr -1
ExceptionAddress: 00007ff6393b4fdc
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000001
   Parameter[1]: 00007ff639350e9c
Attempt to write to address 00007ff639350e9c
0:000> kb
 # RetAddr               : Args to Child                                                           : Call Site
00 00000000`00000000     : 000001c6`b575708c 00000000`0a840665 00007ff6`39461218 00000039`00001134 : 0x00007ff6`393b4fdc
```

Based on my observation, the instrumented code will always be triggered even if the instrumented code got released by uncommenting `TinyInst::OnProcessExit();` in the `LiteCov::PostDetach`. I'm still trying to figure out why the instrumented code is triggered. I was hoping you could shed some light.

Thanks.

**Comment by ifratric** [comment]
Hmm yes it seems that instrumented code is still running. From what I can tell, it crashes when it tries to record coverage (write to the coverage buffer) at 
`mov     byte ptr [00007ff6 39350e9c],1`
The thing with TinyInst is, it relies on exceptions and breakpoints in some cases in the instrumented code, and the debugger is needed to resolve those exceptions. For example above, you're most likely writing coverage to a non-writeable buffer (this is a part of TinyInst's optimization to determine if the target hit new coverage or not). Normally, the debugger would resolve this exception but, as the debugger is detached, there is nobody to resolve it.

If you want to truly restore the target state, then I think you would need to walk all threads of the target and restore the RIP to the corresponding original code locations whenever RIP in instrumented code is encountered. But even that might not be sufficient, as there could be instrumented code pointers on the stack (as return addresses). Running with `-patch_return_addresses` might help with a second problem, but it comes at a performance cost.

**Comment by x9090** [comment]
Thanks for the pointers, that works perfectly! :)
